name: Pages Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Config.js
        run: |
          sed "1i ${{ secrets.CONFIG_FILE }}" chat_test.js
      - name: Deploy
        uses: actions/deploy-pages@v4
