name: Pages Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Config.js
        run: |
          sed '1iconst firebaseConfig = {\napiKey: ${{ secrets.FIREBASE_APIKEY }},\nauthDomain: ${{ secrets.FIREBASE_AUTH_DOMAIN }},\ndatabaseURL: ${{ secrets.FIREBASE_DATABASE_URL }},\nprojectId: ${{ secrets.FIREBASE_PROJECT_ID }},\nstorageBucket: ${{ secrets.FIREBASE_STORAGE_BUCKET }},\nmessagingSenderId: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }},\nappId: ${{ secrets.FIREBASE_APPID }},\nmeasurementId: '${{ secrets.FIREBASE_MEASUREMENT_ID }}'\n};' chat_test.js
      - name: Deploy
        uses: actions/deploy-pages@v4